plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

sidebar:
  - getting-started
  
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
title: Python for geospatial analyses
markdown: GFM
show_downloads: false
theme: just-the-docs

footer_content: "Copyright &copy; 2024 LYW Tang. Distributed by an <a href=\"LICENSE\">MIT license.</a>"

  
# just-the-docs
# jekyll-theme-minimal     <-- blue
# jekyll-theme-hacker      <-- black background with typewriter font
# jekyll-theme-architect   <-- handwriting-like font
# jekyll-theme-merlot      <-- scrolls as decorations
# jekyll-theme-cayman      <-- green/blue top banner 
# jekyll-theme-midnight    <-- dark
# jekyll-theme-leap-day    <-- python colors
# others:                  <-- https://github.com/pages-themes
