title: Zendesk Garden Jekyll Theme
description: A Jekyll theme using the Zendesk Garden design patterns

permalink: pretty

search_enabled: true
auto_page_title: true

mermaid_enabled: true
mermaid_theme: forest

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

  
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  
relative_links:
  enabled: true
  collections: true

sidebar:
  - examples
  - popular-packages
  - resources
  
include:
  - README.md
  - LICENSE.md
  
title: Python for geospatial analyses
show_downloads: false

theme: jekyll-theme-zendesk-garden 
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

footer_content: "Copyright &copy; 2024 LYW Tang. Distributed by an <a href=\"LICENSE\">MIT license.</a>"

  
# just-the-docs
# jekyll-theme-minimal     <-- blue
# jekyll-theme-hacker      <-- black background with typewriter font
# jekyll-theme-architect   <-- handwriting-like font
# jekyll-theme-merlot      <-- scrolls as decorations
# jekyll-theme-cayman      <-- green/blue top banner 
# jekyll-theme-midnight    <-- dark
# jekyll-theme-leap-day    <-- python colors
# others:                  <-- https://github.com/pages-themes
